name: build
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: print env
    - name: my custom action
      uses: angry-cellophane/test-github-action@v1.2
      with:
        name: Alex
