name: build
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    # checks all markdown files from /docs including all subfolders
    with:
      use-quiet-mode: 'yes'
      use-verbose-mode: 'yes'
      folder-path: 'docs/'
