name: build
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
        key: ../pipelines
    - name: print env
      run: env
    - name: print env
      run: env
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
